theme: jekyll-theme-midnight
title: Welcome to Pytroll.org!
plugins:
  # see https://github.com/benbalter/jekyll-relative-links
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
